### ISSUE TITLE
About contrapro.json

### ISSUE THREAD

**Issue by ghost** [ZurichNLP/ContraPro#4]
Please, tell me understand contrapro.json, how to generate this file? Because i refer use your tool to evaluation for another language (ex: en-vi)
Thank you!

**Comment by a-rios** [comment]
Hi, you can just download the .json file, it's part of the repo? Or do you mean how to create one for another language pair?

**Comment by ghost** [comment]
I mean, i want to create another language pair. 
contrapro.json in repo just for en-de. Can I create contrapro.json for en-vi?
Thank you!

**Comment by bricksdont** [comment]
The code we used to extract those examples is currently not available because our Gitlab servers were discontinued. As soon as I manage to upload the code again I will notify you in this thread.

You can in principle then adapt this code for EN-VI, but important: our extraction process relies on many NLP tools such as tagging, parsing and coreference resolution. If such tools are not available for Vietnamese then our approach does not work.

**Comment by a-rios** [comment]
If you have a parallel corpus, you need to parse both sides and do co-reference resolution - then, via word alignment, you can extract sentence pairs that have corresponding pronouns that you can then replace to create the contrastive sentences. 
The tricky part is probably to get a good co-reference resolution, this seems to be something that isn't available for many languages.

**Comment by ghost** [comment]
Thank you!, let me try. VNCoreNLP Tool can  create  Post taging, but can not detect co-reference resolution :(

**Comment by bricksdont** [comment]
Hi @sinhngn,

The code to extract contrapro is up again, here:

https://gitlab.ifi.uzh.ch/mmueller/pronoun-sets

There is not much documentation unfortunately. One file you may be interested in that shows most of the extraction logic is

https://gitlab.ifi.uzh.ch/mmueller/pronoun-sets/-/blob/master/extract.py

Let me know if this is useful and regards
Mathias

**Comment by bricksdont** [comment]
@sinhngn Does the above answer your question, can this issue be closed?

**Comment by ghost** [comment]
Yes, thank you very much!
